// default package
// Generated 29/11/2017 11:28:30 AM by Hibernate Tools 5.2.3.Final

/**
 * SanPost generated by hbm2java
 */
public class SanPost implements java.io.Serializable {

	private Integer pstId;
	private String pstContent;
	private String pstControl;

	public SanPost() {
	}

	public SanPost(String pstContent, String pstControl) {
		this.pstContent = pstContent;
		this.pstControl = pstControl;
	}

	public Integer getPstId() {
		return this.pstId;
	}

	public void setPstId(Integer pstId) {
		this.pstId = pstId;
	}

	public String getPstContent() {
		return this.pstContent;
	}

	public void setPstContent(String pstContent) {
		this.pstContent = pstContent;
	}

	public String getPstControl() {
		return this.pstControl;
	}

	public void setPstControl(String pstControl) {
		this.pstControl = pstControl;
	}

}
